/*modelagem fisica*/
/*CRIANDO O BANCO DE DADOS*/
CREATE DATABASE PROJETO;

CREATE DATABASE EXEMPLO;

/*CONECTANDO-SE AO BANCO*/
USE PROJETO;

/*CRIANDO A TABELA CLIENTES*/
CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);
/*PARA VISUALIZAR TODAS AS TABELAS*/
SHOW TABLES;

/*DESCOBRINDO COMO É A ESTRUTURA DA TABELA*/
DESC CLIENTE;

/* SINTAXE BASICA PARA INSERT NA TABELA */
INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOAO@GMAIL.COM', '1111111111', '984328887', 'MARIA LACERDA - ESTACIO - RIO DE JANEIRO-RJ');
INSERT INTO CLIENTE VALUES ('MARIA', 'F', 'MARIA@GMAIL.COM', '1234567890', '996342871', 'ANTONIO TITO - SOBRINHO - CAMPO GRANDE-RJ');

INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES ('ANGELINA JOLYE', 'F', 'JOLYE@GMAIL.COM', '1234567890', '940028922', 'MARGARIDA - SANTO AMARO - FLORIANOPOLIS-SP');

/*
=====SQL PARA CRIAR O BD ======
*/
CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE CLIENTE(
	COD_CLI INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(40),
	SEXO ENUM ('M','F') NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	CPF VARCHAR(11) NOT NULL  UNIQUE
);

CREATE TABLE TELEFONE (
	COD_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(30) NOT NULL,
	COD_CLI INT,
	FOREIGN KEY(COD_CLI)
	REFERENCES CLIENTE(COD_CLI)
);

CREATE TABLE ENDERECO (
	COD_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	NUMERO VARCHAR(7) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CEP VARCHAR(8),
	COD_CLI INT UNIQUE,
	FOREIGN KEY(COD_CLI)
	REFERENCES CLIENTE(COD_CLI)
);

/*INSERINDO DADOS NA TABELA DE CLIENTE*/
INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF) VALUES ('HUDSON', 'M', 'HUDSON@GMAIL.COM', '12312312387');
INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF) VALUES ('WILSON', 'M', 'WILSON@GMAIL.COM', '14512312387');
INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF) VALUES ('MARIA', 'F', 'MARIA@GMAIL.COM', '11212356387');
INSERT INTO CLIENTE(NOME, SEXO, EMAIL, CPF) VALUES ('FERNANDA', 'F', 'FERNANDA@GMAIL.COM', '31212356388');

/*INSERINDO DADOS NA TABELA DE ENDEREÇO*/
INSERT INTO ENDERECO(RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, COD_CLI) VALUES ('SANTA GERTRUDES', '123', 'SANTA LUZIA', 'CAMPO GRANDE', 'MS','79111330', 1);
INSERT INTO ENDERECO(RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, COD_CLI) VALUES ('SÃO RAMÃO', '623', 'SANTA LUZIA', 'CAMPO GRANDE', 'MS','79116330', 2);
INSERT INTO ENDERECO(RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, COD_CLI) VALUES ('SANTO ANASTACIO', '234', 'SANTA LUZIA', 'CAMPO GRANDE', 'MS','79117330', 3);
INSERT INTO ENDERECO(RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, COD_CLI) VALUES ('SANTA CRISTINA', '74', 'SANTA LUZIA', 'CAMPO GRANDE', 'MS','79118330', 4);

/*INSERINDO DADOS NA TABELA DE ENDEREÇO*/
INSERT INTO TELEFONE(TIPO, NUMERO, COD_CLI) VALUES ('RES', '3365-2926', 1);
INSERT INTO TELEFONE(TIPO, NUMERO, COD_CLI) VALUES ('CEL', '99156-4708', 2);
INSERT INTO TELEFONE(TIPO, NUMERO, COD_CLI) VALUES ('COM', '3365-3456', 1);

/*CONSULTANDO DADOS COM INNER JOIN*/
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON COD_CLI = COD_CLI